norm:
  PileUp_Lumi_MC:
    expression: weight_MC_Lumi_pu{scale}_rel  * final_weight
    name: CMS_pileup_{}
  MuonID_TightID:
    expression: weight_tau1_MuonID_SF_TightID_Trk{scale}_rel * weight_tau2_MuonID_SF_TightID_Trk{scale}_rel * final_weight
    name: MuonID_TightID
  MuonID_TightIDIso:
    expression: weight_tau1_MuonID_SF_LoosePFIso{scale}_rel * weight_tau2_MuonID_SF_LoosePFIso{scale}_rel * final_weight
    name: MuonID_TightIDIso
  HLT_singleMu:
    expression: weight_tau1_TrgSF_singleMu_IsoMu24{scale}_rel * final_weight
    name: HLT_singleMu
  HLT_singleEle:
    expression: weight_tau1_TrgSF_singleEle_singleEle{scale}_rel * final_weight
    name: HLT_singleEle
shape: []