fs_default:
    - 'T3_CH_CERNBOX:/store/user/kandroso/HH_bbtautau_Run3/'
fs_anaCache:
    - 'T3_CH_CERNBOX:/store/user/kandroso/HH_bbtautau_Run3/'
fs_anaTuple:
    - 'T3_CH_CERNBOX:/store/user/kandroso/HH_bbtautau_Run3/'
fs_anaCacheTuple:
    - 'T3_CH_CERNBOX:/store/user/kandroso/HH_bbtautau_Run3/'
fs_histograms:
    - 'T3_CH_CERNBOX:/store/user/kandroso/HH_bbtautau_Run3/histograms/'
fs_json:
- 'T3_CH_CERNBOX:/store/user/kandroso/HH_bbtautau_Run3/jsonFiles/'

analysis_config_area: config
compute_unc_variations: true
compute_unc_histograms: true
store_noncentral: true
vars_to_plot:
- tau1_pt
- tau2_pt
- PV_npvs
- tautau_m_vis
- bb_m_vis
- bbtautau_mass
- { "name" : MT2, need_cache: true }
# - { "name": SVfit_m, need_cache: true }
# - { "name": kinFit_m, need_cache: true }